sudo: required
services:
  - docker

before_install:
  - docker build -t vladdr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vladdr/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-185290816834"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master